# Generated by Django 5.2.8 on 2025-11-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
